#!/bin/bash
if [ -z "$1" ]
then 
  TARGET=$HOME
else
  TARGET=$1
fi

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

ln -sf $DIR/bash_profile $TARGET/.bash_profile
ln -sf $DIR/profile/bin/ $TARGET/bin
ln -sf $DIR/bashrc $TARGET/.bashrc
ln -sf $DIR/gemrc $TARGET/.gemrc
ln -sf $DIR/vimrc $TARGET/.vimrc
ln -sf $DIR/gitignore_global $TARGET/.gitignore_global

if [ ! -d $TARGET/.vim ]; then ln -s $DIR/vim $TARGET/.vim > /dev/null 2>&1; fi
