#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

ln -sf $DIR/bash_profile ~/.bash_profile
ln -sf $DIR/bashrc ~/.bashrc
ln -sf $DIR/gemrc ~/.gemrc
ln -sf $DIR/vim ~/.vim
ln -sf $DIR/vimrc ~/.vimrc
ln -sf $DIR/gitignore_global ~/.gitignore_global