#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

ln -sf $DIR/bash_profile $HOME/.bash_profile
ln -sf $DIR/bashrc $HOME/.bashrc
ln -sf $DIR/gemrc $HOME/.gemrc
ln -sf $DIR/vimrc $HOME/.vimrc
ln -sf $DIR/gitignore_global $HOME/.gitignore_global

if [ ! -d $HOME/.vim ]; then ln -s $DIR/vim $HOME/.vim > /dev/null 2>&1; fi
